"use client";

import React, { useState } from "react";
import Link from "next/link";
import {
  FileText,
  ArrowLeft,
  Sparkles,
  Download,
  BookOpen,
  Wand2,
  Copy,
  Check,
} from "lucide-react";

export default function DocumentsStudioPage() {
  const [content, setContent] = useState(`# Yash.AI Project Specification

## Overview
Yash.AI is a unified AI creation platform integrating multi-provider conversational intelligence with specialized creative studios.

### Key Milestones
1. **Platform Core & Universal Assets**: S3 Presigned URLs + Local Storage.
2. **Tool Execution Gateway**: SSRF protection, granular permissions, human confirmation.
3. **Dedicated Workspaces**: Image, Video, 3D, Canvas, Code, Audio, Documents, and Research.
`);
  const [summarizing, setSummarizing] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleAiSummarize = () => {
    setSummarizing(true);
    setTimeout(() => {
      setContent((prev) => `${prev}\n\n### Executive Summary (Generated by AI)\nYash.AI unifies creative generation into a single secure platform with full project persistence.`);
      setSummarizing(false);
    }, 800);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "yash_ai_document.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-black text-white flex flex-col font-sans">
      {/* Studio Header */}
      <header className="h-14 border-b border-zinc-800/80 px-6 flex items-center justify-between bg-zinc-950/80 backdrop-blur-sm sticky top-0 z-30">
        <div className="flex items-center gap-3">
          <Link
            href="/create"
            className="p-1.5 rounded-xl bg-zinc-900 hover:bg-zinc-800 text-zinc-400 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
          </Link>
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center text-indigo-400">
              <FileText className="w-4 h-4" />
            </div>
            <span className="font-bold text-sm text-zinc-100">Yash.AI Docs Studio</span>
            <span className="text-[10px] px-2 py-0.5 rounded-full bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 font-semibold">
              Markdown & Docs
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleAiSummarize}
            disabled={summarizing}
            className="flex items-center gap-1.5 py-1.5 px-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white text-xs font-semibold shadow-md shadow-indigo-600/20 transition-all cursor-pointer"
          >
            <Wand2 className="w-3.5 h-3.5" />
            <span>{summarizing ? "Summarizing..." : "AI Summarize"}</span>
          </button>
          <button
            onClick={handleCopy}
            className="p-1.5 rounded-xl bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-xs font-medium text-zinc-300 transition-colors"
            title="Copy Markdown"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
          </button>
          <button
            onClick={handleExport}
            className="flex items-center gap-1.5 py-1.5 px-3 rounded-xl bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-xs font-semibold text-zinc-200 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export MD</span>
          </button>
        </div>
      </header>

      {/* Editor & Preview Split View */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-2 overflow-hidden">
        {/* Editor Area */}
        <div className="border-r border-zinc-800/80 p-6 flex flex-col bg-zinc-950">
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            className="flex-1 w-full bg-transparent font-mono text-xs text-zinc-200 resize-none focus:outline-none leading-relaxed"
            placeholder="Type your markdown document..."
          />
        </div>

        {/* Live Preview Area */}
        <div className="p-8 bg-black overflow-y-auto prose prose-invert prose-zinc max-w-none text-xs">
          <div className="max-w-2xl mx-auto space-y-4 text-zinc-300">
            {content.split("\n").map((line, idx) => {
              if (line.startsWith("# ")) {
                return <h1 key={idx} className="text-xl font-bold text-white border-b border-zinc-800 pb-2">{line.replace("# ", "")}</h1>;
              }
              if (line.startsWith("## ")) {
                return <h2 key={idx} className="text-base font-bold text-zinc-100 pt-2">{line.replace("## ", "")}</h2>;
              }
              if (line.startsWith("### ")) {
                return <h3 key={idx} className="text-sm font-semibold text-zinc-200">{line.replace("### ", "")}</h3>;
              }
              if (line.startsWith("- ") || line.startsWith("1. ")) {
                return <li key={idx} className="ml-4 list-disc text-zinc-300">{line.replace(/^[-1.]\s*/, "")}</li>;
              }
              if (line.trim() === "") return <div key={idx} className="h-2" />;
              return <p key={idx} className="leading-relaxed">{line}</p>;
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
